// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAUTv_wcSue6F6fltEEtfBSuYgS7svMQhA',
    appId: '1:225479992557:web:aefbc4e4049d21979458e4',
    messagingSenderId: '225479992557',
    projectId: 'fluttermidhackthon',
    authDomain: 'fluttermidhackthon.firebaseapp.com',
    storageBucket: 'fluttermidhackthon.appspot.com',
    measurementId: 'G-TJNG0LD7M1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCZu3CN6g_IacD1456S5lvAv_dUKMtv-Hs',
    appId: '1:225479992557:android:b88ac0bdd54b906b9458e4',
    messagingSenderId: '225479992557',
    projectId: 'fluttermidhackthon',
    storageBucket: 'fluttermidhackthon.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBhBbKUPSEqTB6p6oZtrQnbW_9yNVPrZfs',
    appId: '1:225479992557:ios:71eb362211c0a6369458e4',
    messagingSenderId: '225479992557',
    projectId: 'fluttermidhackthon',
    storageBucket: 'fluttermidhackthon.appspot.com',
    iosBundleId: 'com.example.fluttermidhackathon',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBhBbKUPSEqTB6p6oZtrQnbW_9yNVPrZfs',
    appId: '1:225479992557:ios:71eb362211c0a6369458e4',
    messagingSenderId: '225479992557',
    projectId: 'fluttermidhackthon',
    storageBucket: 'fluttermidhackthon.appspot.com',
    iosBundleId: 'com.example.fluttermidhackathon',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAUTv_wcSue6F6fltEEtfBSuYgS7svMQhA',
    appId: '1:225479992557:web:491d30cfe5a321b79458e4',
    messagingSenderId: '225479992557',
    projectId: 'fluttermidhackthon',
    authDomain: 'fluttermidhackthon.firebaseapp.com',
    storageBucket: 'fluttermidhackthon.appspot.com',
    measurementId: 'G-DB7YCRNXYR',
  );
}
